from django.db.models import Count, Q
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import filters, mixins, viewsets
from rest_framework.permissions import IsAuthenticated
from rest_framework.views import APIView

from accounts.models import User
from accounts.permissions import IsAdminUserRole
from config.responses import success_response
from menu.models import Category, Product, Product3DModel
from restaurants.models import Restaurant

from .serializers import (
    AdminCategorySerializer,
    AdminDashboardSerializer,
    AdminProduct3DModelSerializer,
    AdminProductSerializer,
    AdminRestaurantSerializer,
    AdminUserSerializer,
)


class _AdminPermissionMixin:
    """Requires authentication + ADMIN role on every action."""

    permission_classes = [IsAuthenticated, IsAdminUserRole]


class _AdminListMixin(_AdminPermissionMixin):
    """Wraps `list` in the platform's standard response envelope. Only mix this
    in (with mixins.ListModelMixin) for read-only, list-only endpoints."""

    def list(self, request, *args, **kwargs):
        queryset = self.filter_queryset(self.get_queryset())
        page = self.paginate_queryset(queryset)
        serializer = self.get_serializer(page if page is not None else queryset, many=True)
        data = serializer.data
        if page is not None:
            return self.get_paginated_response(data)
        return success_response(data=data)


class _AdminRetrieveMixin:
    """Only mix in alongside mixins.RetrieveModelMixin — adds nothing unless a
    retrieve route is also generated by the router."""

    def retrieve(self, request, *args, **kwargs):
        instance = self.get_object()
        return success_response(data=self.get_serializer(instance).data)


class _AdminUpdateMixin:
    """Only mix in alongside mixins.UpdateModelMixin."""

    def update(self, request, *args, **kwargs):
        partial = kwargs.pop("partial", False)
        instance = self.get_object()
        serializer = self.get_serializer(instance, data=request.data, partial=partial)
        serializer.is_valid(raise_exception=True)
        updated = serializer.save()
        return success_response(
            data=self.get_serializer(updated).data,
            message=f"{self.entity_name} updated successfully.",
        )


class _AdminDestroyMixin:
    """Only mix in alongside mixins.DestroyModelMixin."""

    def destroy(self, request, *args, **kwargs):
        instance = self.get_object()
        instance.delete()
        return success_response(message=f"{self.entity_name} deleted successfully.")


class AdminDashboardView(APIView):
    """GET /api/v1/admin/dashboard/ — platform-wide counts in a single efficient query set."""

    permission_classes = [IsAuthenticated, IsAdminUserRole]

    def get(self, request):
        user_counts = User.objects.aggregate(total=Count("id"))
        restaurant_counts = Restaurant.objects.aggregate(
            total=Count("id"),
            published=Count("id", filter=Q(is_published=True)),
        )
        category_counts = Category.objects.aggregate(total=Count("id"))
        product_counts = Product.objects.aggregate(
            total=Count("id"),
            available=Count("id", filter=Q(is_available=True)),
        )
        model_counts = Product3DModel.objects.aggregate(total=Count("id"))

        data = {
            "total_users": user_counts["total"],
            "total_restaurants": restaurant_counts["total"],
            "published_restaurants": restaurant_counts["published"],
            "unpublished_restaurants": restaurant_counts["total"] - restaurant_counts["published"],
            "total_categories": category_counts["total"],
            "total_products": product_counts["total"],
            "available_products": product_counts["available"],
            "total_3d_models": model_counts["total"],
        }
        return success_response(data=AdminDashboardSerializer(data).data)


class AdminUserViewSet(
    _AdminListMixin,
    _AdminRetrieveMixin,
    _AdminUpdateMixin,
    mixins.ListModelMixin,
    mixins.RetrieveModelMixin,
    mixins.UpdateModelMixin,
    viewsets.GenericViewSet,
):
    """/api/v1/admin/users/ — view all users and activate/deactivate them.
    Password, email, name, and role are never editable from this endpoint."""

    queryset = User.objects.all().order_by("-created_at")
    serializer_class = AdminUserSerializer
    entity_name = "User"
    filter_backends = [DjangoFilterBackend, filters.SearchFilter]
    filterset_fields = ["role", "is_active"]
    search_fields = ["email", "first_name", "last_name"]
    http_method_names = ["get", "patch", "head", "options"]


class AdminRestaurantViewSet(
    _AdminListMixin,
    _AdminRetrieveMixin,
    _AdminUpdateMixin,
    _AdminDestroyMixin,
    mixins.ListModelMixin,
    mixins.RetrieveModelMixin,
    mixins.UpdateModelMixin,
    mixins.DestroyModelMixin,
    viewsets.GenericViewSet,
):
    """/api/v1/admin/restaurants/ — full platform visibility and management."""

    queryset = Restaurant.objects.select_related("owner").order_by("-created_at")
    serializer_class = AdminRestaurantSerializer
    entity_name = "Restaurant"
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ["city", "is_published", "is_active"]
    search_fields = ["name", "city", "address", "owner__email"]
    ordering_fields = ["created_at", "name"]


class AdminCategoryViewSet(_AdminListMixin, mixins.ListModelMixin, viewsets.GenericViewSet):
    """/api/v1/admin/categories/ — read-only platform-wide category listing."""

    queryset = (
        Category.objects.select_related("restaurant")
        .annotate(products_count=Count("products"))
        .order_by("restaurant__name", "sort_order")
    )
    serializer_class = AdminCategorySerializer
    entity_name = "Category"
    filter_backends = [DjangoFilterBackend, filters.SearchFilter]
    filterset_fields = ["restaurant", "is_active"]
    search_fields = ["name", "restaurant__name"]


class AdminProductViewSet(_AdminListMixin, mixins.ListModelMixin, viewsets.GenericViewSet):
    """/api/v1/admin/products/ — read-only platform-wide product listing."""

    queryset = (
        Product.objects.select_related("restaurant", "category")
        .prefetch_related("model_3d")
        .order_by("restaurant__name", "sort_order")
    )
    serializer_class = AdminProductSerializer
    entity_name = "Product"
    filter_backends = [DjangoFilterBackend, filters.SearchFilter]
    filterset_fields = ["restaurant", "category", "is_available", "is_featured"]
    search_fields = ["name", "restaurant__name", "category__name"]


class AdminProduct3DModelViewSet(_AdminListMixin, mixins.ListModelMixin, viewsets.GenericViewSet):
    """/api/v1/admin/3d-models/ — read-only platform-wide 3D model listing."""

    queryset = Product3DModel.objects.select_related("product", "product__restaurant").order_by("-created_at")
    serializer_class = AdminProduct3DModelSerializer
    entity_name = "3D Model"
    filter_backends = [DjangoFilterBackend, filters.SearchFilter]
    filterset_fields = ["format", "is_ar_enabled", "product__restaurant"]
    search_fields = ["product__name", "product__restaurant__name"]
